export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR'
export const GET_NOTIFICATION_COUNT_SUCCESS = 'GET_NOTIFICATION_COUNT_SUCCESS'

export const GET_LAST_NOTIFICATION_REQUEST = 'GET_LAST_NOTIFICATION_REQUEST'
export const GET_LAST_NOTIFICATION_SUCCESS = 'GET_LAST_NOTIFICATION_SUCCESS'
export const GET_LAST_NOTIFICATION_ERROR = 'GET_LAST_NOTIFICATION_ERROR'
export const GET_LAST_NOTIFICATION_COUNT_SUCCESS = 'GET_LAST_NOTIFICATION_COUNT_SUCCESS'

export const GET_SUBSCRIPTION_REQUEST = 'GET_SUBSCRIPTION_REQUEST'
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS'
export const GET_SUBSCRIPTION_ERROR = 'GET_SUBSCRIPTION_ERROR'
export const GET_SUBSCRIPTION_COUNT_SUCCESS = 'GET_SUBSCRIPTION_COUNT_SUCCESS'

export const GET_LAST_SUBSCRIPTION_REQUEST = 'GET_LAST_SUBSCRIPTION_REQUEST'
export const GET_LAST_SUBSCRIPTION_SUCCESS = 'GET_LAST_SUBSCRIPTION_SUCCESS'
export const GET_LAST_SUBSCRIPTION_ERROR = 'GET_LAST_SUBSCRIPTION_ERROR'
export const GET_LAST_SUBSCRIPTION_COUNT_SUCCESS = 'GET_LAST_SUBSCRIPTION_COUNT_SUCCESS'

export const GET_SUBIDS_REQUEST = 'GET_SUBIDS_REQUEST'
export const GET_SUBIDS_ERROR = 'GET_SUBIDS_ERROR'
export const GET_SUBIDS_SUCCESS = 'GET_SUBIDS_SUCCESS'
